---
swagger: "2.0"
info:
  description: "This is a sample server Book Store server."
  version: "1.0.5"
  title: "Swagger Bookstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "192.168.65.10:8080"
basePath: "/mocks"
tags:
- name: "book"
  description: "Access to book"
- name: "author"
  description: "Everything about your author"
schemes:
- "http"
- "https"
paths:
  /book/{isbn}:
    get:
      tags:
      - "book"
      summary: "Find a book by ISBN"
      description: "Returns a single book"
      operationId: "getBookByIsbn"
      consumes:
        - "application/json"      
      produces:
      - "application/json"
      parameters:
      - name: "isbn"
        in: "path"
        description: "ISBN of book to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/definitions/Book"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Book not found"
      security:
      - store_auth:
        - "write:books"
        - "read:books"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
  store_auth:
    type: "oauth2"
    authorizationUrl: "https://petstore.swagger.io/oauth/authorize"
    flow: "implicit"
    scopes:
      read:books: "read your books"
      write:books: "modify books in your account"
definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  Book:
    type: "object"
    required:
    - "title"
    - "subtitle"
    - "isbn13"
    properties:
      isbn13:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "title"
      subtitle:
        type: "string"
        example: "sub title"
    json:
      name: "Book"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"